// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tullur/lets-go-chat/internal/service"
)

// Injectors from wire.go:

func NewUser(dbHost string) (*service.UserService, error) {
	userService, err := initializeUserService(dbHost)
	if err != nil {
		return nil, err
	}
	return userService, nil
}

func NewChat(dbHost string) (*service.ChatService, error) {
	chatService, err := initializeChatService(dbHost)
	if err != nil {
		return nil, err
	}
	return chatService, nil
}

// wire.go:

func initializeUserService(dbHost string) (*service.UserService, error) {
	userService, err := service.NewUserService(service.WithMongoRepository(dbHost))
	if err != nil {
		return nil, err
	}

	return userService, nil
}

func initializeChatService(dbHost string) (*service.ChatService, error) {
	chatService, err := service.NewChatService(service.WithInMemoryTokenRepository(), service.WithMessageMongoRepository(dbHost))
	if err != nil {
		return nil, err
	}

	return chatService, nil
}
