// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tullur/lets-go-chat/internal/service"
)

// Injectors from wire.go:

func NewUser(connection string) (*service.UserService, error) {
	userConfiguration := service.WithMongoRepository(connection)
	userService, err := service.NewUserService(userConfiguration)
	if err != nil {
		return nil, err
	}
	return userService, nil
}
